services:
  postgres:
    image: postgres:16
    container_name: edk_postgres
    ports:
      - '5432:5432'
    command:
      - 'postgres'
      - '-c'
      - 'default_toast_compression=lz4'
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-edk}
      POSTGRES_USER: ${POSTGRES_USER:-edk_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-edk_password}
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    networks:
      - edk_network
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: edk_redis
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis_password}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis_password}
    volumes:
      - ./.data/redis:/data
    networks:
      - edk_network
    restart: unless-stopped

  typesense:
    image: typesense/typesense:0.25.2
    container_name: edk_typesense
    ports:
      - '8108:8108'
    environment:
      - TYPESENSE_DATA_DIR=/data
      - TYPESENSE_API_KEY=${TYPESENSE_API_KEY:-xyz}
    volumes:
      - ./.data/typesense:/data
    networks:
      - edk_network
    restart: unless-stopped

networks:
  edk_network:
    driver: bridge
