services:
  postgres:
    image: postgres:16
    container_name: edk_postgres
    ports:
      - '5432:5432'
    command:
      - 'postgres'
      - '-c'
      - 'default_toast_compression=lz4'
      - '-c'
      - 'max_locks_per_transaction=1024'
      - '-c'
      - 'shared_buffers=256MB'
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-edk}
      POSTGRES_USER: ${POSTGRES_USER:-edk_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-edk_password}
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    networks:
      - edk_network
    restart: unless-stopped

  redis-cache:
    image: redis:latest
    container_name: edk_redis_cache
    ports:
      - '6379:6379'
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD:-redis_password}
      --maxmemory 4gb
      --maxmemory-policy allkeys-lru
      --save ""
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis_password}
    networks:
      - edk_network
    restart: unless-stopped

  redis-queue:
    image: redis:latest
    container_name: edk_redis_queue
    ports:
      - '6380:6379'
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD:-redis_password}
      --save 900 1
      --save 300 10
      --save 60 10000
      --appendonly yes
      --appendfsync everysec
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis_password}
    volumes:
      - ./.data/redis-queue:/data
    networks:
      - edk_network
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: edk_prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - edk_network
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: edk_grafana
    ports:
      - '3001:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./.data/grafana:/var/lib/grafana
    networks:
      - edk_network
    restart: unless-stopped

networks:
  edk_network:
    driver: bridge
