{{- if .Values.deployJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "edk.fullname" . }}-deploy-{{ .Release.Revision }}
  labels:
    app.kubernetes.io/name: {{ include "edk.name" . }}
    app.kubernetes.io/component: deploy-job
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "edk.name" . }}
        app.kubernetes.io/component: deploy-job
    spec:
      restartPolicy: Never
      containers:
        - name: edk-deploy
          image: "{{ .Values.global.image.registry }}/{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              echo "Running DB migrations"
              bun cli db:migrate
              echo "Downloading SDE"
              bun cli sde:download
              echo "Refreshing DB materialized views"
              bun cli db:refresh
          env:
            {{- include "edk.commonEnv" . | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /app/.data
      volumes:
        - name: data
          emptyDir: {}
      backoffLimit: 1
  ttlSecondsAfterFinished: 3600
{{- end }}
