{{- if .Values.gateway.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "edk.fullname" . }}
  labels:
    {{- include "edk.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ .Values.gateway.gatewayClassName }}
    namespace: {{ .Release.Namespace }}
  hostnames:
  {{- range .Values.gateway.httpRoute.hostnames }}
  - {{ . | quote }}
  {{- end }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ include "edk.fullname" . }}-web
      port: {{ .Values.web.service.port }}
{{- end }}
