{{- if .Values.database.createCluster }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-postgres-optimized
  labels:
    {{- include "edk.labels" . | nindent 4 }}
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  dataLocality: "strict-local"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: "ext4"
  dataEngine: "v1"
  disableRevisionCounter: "true"
{{- end }}
