{{- if .Values.redisq.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "edk.fullname" . }}-redisq
  labels:
    app.kubernetes.io/name: {{ include "edk.name" . }}
    app.kubernetes.io/component: redisq
spec:
  replicas: {{ .Values.redisq.replicaCount | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "edk.name" . }}
      app.kubernetes.io/component: redisq
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "edk.name" . }}
        app.kubernetes.io/component: redisq
    spec:
      containers:
        - name: edk-redisq
          image: "{{ .Values.global.image.registry }}/{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          command: ["bun", "cli", "redisq"]
          env:
            {{- include "edk.commonEnv" . | nindent 12 }}
          resources:
            {{- toYaml .Values.redisq.resources | nindent 12 }}
      restartPolicy: Always
{{- end }}
