{{- if .Values.websocket.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "edk.fullname" . }}-websocket
  labels:
    {{- include "edk.labels" . | nindent 4 }}
    app.kubernetes.io/component: websocket
spec:
  replicas: {{ .Values.websocket.replicaCount }}
  selector:
    matchLabels:
      {{- include "edk.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: websocket
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "edk.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: websocket
    spec:
      {{- with .Values.global.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "edk.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: websocket
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.global.image.registry }}/{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        command: ["bun", "ws.ts"]
        env:
          {{- include "edk.commonEnv" . | nindent 10 }}
        resources:
          {{- toYaml .Values.websocket.resources | nindent 12 }}
        volumeMounts:
        - name: data
          mountPath: /app/.data
      volumes:
      - name: data
        emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
