apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: edk
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/EVE-KILL/edk
  ref:
    branch: main
  secretRef:
    name: github-credentials
