apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: edk
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./chart
      sourceRef:
        kind: GitRepository
        name: edk
        namespace: flux-system
      interval: 1m
  releaseName: edk
  targetNamespace: eve-kill
  install:
    createNamespace: true
  upgrade:
    force: true
  valuesFrom:
    - kind: Secret
      name: edk-values
      valuesKey: values.yaml
