apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: edk
  namespace: flux-system
spec:
  image: ghcr.io/eve-kill/edk
  interval: 1m
  secretRef:
    name: ghcr-credentials
