apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: edk
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: edk
  update:
    strategy: Setters
    path: ./chart
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        [ci skip] Update EDK image to {{range .Updated.Images}}{{println .}}{{end}}
    push:
      branch: main
