{{- if and .Values.imageserver.enabled .Values.imageserver.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "edk.fullname" . }}-imageserver
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "edk.labels" . | nindent 4 }}
    app.kubernetes.io/component: imageserver
  {{- with .Values.imageserver.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.imageserver.ingress.className }}
  {{- if .Values.imageserver.ingress.tls }}
  tls:
    {{- range .Values.imageserver.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.imageserver.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "edk.fullname" $ }}-imageserver
                port:
                  number: {{ $.Values.imageserver.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
