{{- if .Values.imageserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edk.fullname" . }}-imageserver
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "edk.labels" . | nindent 4 }}
    app.kubernetes.io/component: imageserver
spec:
  type: ClusterIP
  selector:
    {{- include "edk.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: imageserver
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.imageserver.service.port }}
      targetPort: {{ .Values.imageserver.service.targetPort }}
{{- end }}
